#Sensor Subsystem for the DHT22
CONFIG_SENSOR=y

#Hardware Counter Subsystem for the latency interrupts
CONFIG_COUNTER=y

#Hardware features
CONFIG_GPIO=y

#CPU and Thread Monitoring for cpu_monitor.c
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_SCHED_THREAD_USAGE_ALL=y

#Memory Profiling for mem_profile.c
CONFIG_THREAD_MONITOR=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y
CONFIG_HEAP_MEM_POOL_SIZE=32768

#Filesystem and SD Card for fs_bench.c
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_SPI=y
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SDHC=y
CONFIG_DISK_DRIVER_SDMMC=y

#Boot Recovery and Watchdog for boot_recovery.c
CONFIG_WATCHDOG=y
CONFIG_RETAINED_MEM=y

#Enable the Timing API
CONFIG_TIMING_FUNCTIONS=y

#USB Console and Serial
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=y

#Do not print to the USB console before the host connects
CONFIG_BOOT_BANNER=n

#Config system clock
CONFIG_SYS_CLOCK_TICKS_PER_SEC=1000

#Logging and Output Formatting
CONFIG_CBPRINTF_FP_SUPPORT=y

#IPv4 Networking
#CONFIG_NETWORKING=y
#CONFIG_NET_IPV4=y
#CONFIG_NET_UDP=y
#CONFIG_NET_SOCKETS=y
#CONFIG_WIFI=y

#DHCP and Connection Management
#CONFIG_NET_DHCPV4=y
#CONFIG_NET_L2_WIFI_MGMT=y

#Set Wi-Fi Credentials
#CONFIG_WIFI_CREDENTIALS=y
#CONFIG_WIFI_CREDENTIALS_STATIC=y
#CONFIG_WIFI_CREDENTIALS_STATIC_SSID="PicoTest"
#CONFIG_WIFI_CREDENTIALS_STATIC_PASSWORD="8wQ9h0T63fhet910"
#CONFIG_WIFI_CREDENTIALS_STATIC_TYPE_PSK=y

#Automatically connect on boot
#CONFIG_NET_CONFIG_SETTINGS=y
#CONFIG_NET_CONFIG_AUTO_INIT=y

#Give the background threads enough memory to load the CYW43439 firmware
#CONFIG_HEAP_MEM_POOL_SIZE=98304
#CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=8192
#CONFIG_NET_TX_STACK_SIZE=8192
#CONFIG_NET_RX_STACK_SIZE=8192