#Sensor Subsystem for the DHT22
CONFIG_SENSOR=y

#Hardware Counter Subsystem for the latency interrupts
CONFIG_COUNTER=y

#IPv4 Networking
CONFIG_NETWORKING=y
CONFIG_NET_IPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_WIFI=y

#Hardware features
CONFIG_GPIO=y

#CPU and Thread Monitoring for cpu_monitor.c
CONFIG_THREAD_RUNTIME_STATS=y
CONFIG_SCHED_THREAD_USAGE=y
CONFIG_SCHED_THREAD_USAGE_ALL=y

#Memory Profiling for mem_profile.c
CONFIG_THREAD_MONITOR=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_INIT_STACKS=y

#Filesystem and SD Card for fs_bench.c
CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_SPI=y

#Boot Recovery and Watchdog for boot_recovery.c
CONFIG_WATCHDOG=y
CONFIG_RETAINED_MEM=y

#Enable the Timing API
CONFIG_TIMING_FUNCTIONS=y